### PR TITLE
Bug/progress bar not visible

### LINKED ISSUE #265: Progress bar not visible if not connected
Not connected:

Connected:

### LINKED ISSUE #266: Sale has no progress bar if zero purchase yet
https://www.mesa-ui.dev/sales/0x9e83193e6b894d154b536120b524f440819dae50

After first purchase progress bar shows up:

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---
* closes #265 
* closes #266 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/views/Sale/components/HeaderClaim/index.tsx [hunk 1]
```diff
@@ -45,6 +45,7 @@ export function HeaderClaim({ sale }: HeaderClaimProps) {
   const { error: claimError, claim, claimTokens, withdrawTokens } = useTokenClaim()
   const threshold = BigNumber.from(sale.minimumRaise)
   const tokensSold = BigNumber.from(sale.soldAmount)
+  console.log(sale)
```
Comment (rossneilson) [inline src/views/Sale/components/HeaderClaim/index.tsx:48]: Console log here

**Review by rossneilson — APPROVED** [review]
