### PR TITLE
Bug/progress bar

### LINKED ISSUE #252: Progress Bar not updated
Purchase List has updated after tx, but not progress bar, It should show 3.2, it will be rounded down to 3, but I think that's okey here?

By touching this code, please make this adjust too:

Wrapped-XDAI-Mesa (1)

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* closes #252 
* progress bar and its contents update according to each bid
* Min threshold circle changed from grey to white
* Min threshold now also moves along with the circle point
* Fixed previous bugs

## How Has This Been Tested?
Tested Manually by buying tokens

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rossneilson** [comment]
スクリーンショット 2021-06-17 19 17 40

I seem to get some strange CSS on a closed sale

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 1]
```diff
@@ -146,7 +146,7 @@ export function SelfBidList({ sale, clearingPrice, bids, isFixed }: SelfBidListP
 
         {bids.map((bid: FixedPriceSalePurchase, index: number) => {
           const bidValue =
-            formatBigInt(sale.tokenPrice, sale.tokenOut.decimals) * formatBigInt(bid.amount, sale.tokenOut.decimals)
+            formatBigInt(sale.tokenPrice, sale.tokenIn.decimals) * formatBigInt(bid.amount, sale.tokenOut.decimals)
```
Comment (rossneilson) [inline src/views/Sale/components/SelfBidList/index.tsx:149]: Is this supposed to fix the issue we found the other day?

If so I think it is still broken. The below shows the UI but the amount I put in and withdrew out was equal to 1.1, which is not what the UI screenshot suggests. I think you might have gotten it the wrong way around.

Current (what the UI values, currently in this branch, add up to):
Totals- 1.1 FPST 0.55 DAI

Correct (what the values should show):
Totals- 2.2FPST 1.1 DAI

**Comment by martinkrung** [comment]
Made two small changes

- threshold -> soft cap
- DAI -> WXDAI
Screenshot at 2021-06-18 10-46-52

File: src/views/Sale/components/SelfBidList/index.tsx (hunk 1 above)
Comment (hhamud) [reply src/views/Sale/components/SelfBidList/index.tsx:149]: No, those changes were supposed to be stashed as it was later found out that in this [component](https://github.com/cryptonative-ch/mesa-interface/blob/24862705a26379c481ad69ead2b4270abef4438b/src/views/Sale/components/PurchaseTokensForm/index.tsx#L140), that it's being denominated in the input token rather than the amount being denominated in the Output token. The smart contracts [input amount](https://github.com/cryptonative-ch/mesa-smartcontracts/blob/26a59272a7014c41dbb88616b9fa0736ef1a94b8/contracts/sales/FixedPriceSale.sol#L171-L190) is denominated in  `tokenOut` as you can see that it directly makes a comparison between the user amount and the [`allocationMax` and `allocationMin`](https://github.com/cryptonative-ch/mesa-smartcontracts/blob/26a59272a7014c41dbb88616b9fa0736ef1a94b8/contracts/sales/FixedPriceSale.sol#L71-L72),

**Review by rossneilson — APPROVED** [review]
