### PR TITLE
Bug/subgraph claim

### LINKED ISSUE #400: Handle withdraws field from subgraph
As far as I can tell we are not currently handling withdraws field on sales in the UI.
This means that when tokens are claimed the UI reflects the withdrawal. However upon refresh the UI reverts back to unclaimed as it does not check to see if the user has withdrawn their tokens.

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* Closes #400 
* refactored `SelfBidList` Component
* Disabled Claim button on `PROCESSED` tokens

image

## How Has This Been Tested?
Manually Tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 1]
```diff
@@ -20,120 +20,161 @@ import { Table } from 'src/components/Table'
...
+                        (sale as GetFixedPriceSaleCommitmentsByUser_fixedPriceSaleCommitments_sale).tokenPrice,
+                        sale.tokenOut.decimals
+                      ) * formatBigInt((bids as FixedPriceSalePurchase).amount, sale.tokenOut.decimals)
+                    ).format('0.[0000]') +
+                    ' ' +
+                    sale.tokenOut.symbol,
+                  amount:
+                    numeral(formatBigInt((bids as FixedPriceSalePurchase).amount, sale.tokenOut.decimals)).format(
+                      '0.[0000]'
+                    ) +
```
Comment (rossneilson) [inline src/views/Sale/components/SelfBidList/index.tsx:61]: This value formatting could potentially be done by a helper function in future to keep this component cleaner, still this switch is a lot cleaner than before, good job

**Review by rossneilson — APPROVED** [review]
Works well, good job!
