### PR TITLE
Bug/claimtokens

### LINKED ISSUE #277: When Claiming tokens, Tokens are not removed from view
## Description
Claiming tokens does not remove them from both view page

## Expected Behavior
When claiming or withdrawing failed tokens, they must be removed from all views.

## Actual Behavior
Claiming tokens does not remove them from both view page

## Possible Fix
UP TO THE DEVELOPER

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* Closes #277 
* Implements the new changes from the subgraph that updates the status of a purchase, (submitted, claimed) onto the front end interface. 

## How Has This Been Tested?
Manually

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rossneilson** [comment]
スクリーンショット 2021-07-06 21 26 53
Seems to be an issue

File: __generated__/globalTypes.ts [hunk 1]
```diff
@@ -7,6 +7,13 @@
 // START Enums and Input Objects
```
Comment (adamazad) [inline __generated__/globalTypes.ts:7]: Move these types to [`src/subgraph/__generated__`](https://github.com/cryptonative-ch/mesa-interface/tree/dev/src/subgraph/__generated__)

File: src/components/Table/index.tsx [hunk 2]
```diff
@@ -76,26 +77,45 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
         >
           {bodyData.map(({ purchases, color, title }) =>
             purchases.map((purchase: any, index) => {
+              console.log(purchase)
```
Comment (adamazad) [inline src/components/Table/index.tsx:80]: Remove console statements

File: src/components/Table/index.tsx [hunk 3]
```diff
@@ -76,26 +77,45 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
                     <TokenPriceLabel color={color}>{title}</TokenPriceLabel>
                   </TableColumn>
-                  {Object.getOwnPropertyNames(purchase).map((element: any, _index) => {
-                    return (
-                      <TableColumn key={_index}>
-                        <TokenPriceLabel>{purchase[element]}</TokenPriceLabel>
-                      </TableColumn>
-                    )
-                  })}
+                  {Object.getOwnPropertyNames(purchase)
```
Comment (adamazad) [inline src/components/Table/index.tsx:86]: Use `Object.entries` please. This is not readable.

File: src/components/Table/index.tsx [hunk 4]
```diff
@@ -76,26 +77,45 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
+                              src={Tick}
+                              color="#4B9E98"
+                              margin={isMobile ? '4px 32px 4px 0px' : '4px 4px 4px 8px'}
+                            />,
+                            !isMobile && (
+                              <TokenPriceLabel color="#4B9E98" padding="4px 8px 4px 0">
+                                Claimed
+                              </TokenPriceLabel>
+                            ),
+                          ]
```
Comment (adamazad) [inline src/components/Table/index.tsx:109]: Use fragments

File: src/components/Table/index.tsx [hunk 5]
```diff
@@ -76,26 +77,45 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
+                        : [
+                            <IconImg src={WarningSVG} margin={'4px 4px 4px 8px'} />,
+
+                            !isMobile && (
+                              <TokenPriceLabel color="#000629" padding="4px 8px 4px 0">
+                                Unclaimed
+                              </TokenPriceLabel>
+                            ),
+                          ]}
```
Comment (adamazad) [inline src/components/Table/index.tsx:118]: fragments

File: src/subgraph/Sales/index.ts [hunk 6]
```diff
@@ -38,7 +38,7 @@ export const salesQuery = `
       status
       startDate
       endDate
-      tokenAmount
+      tokensForSale
```
Comment (adamazad) [inline src/subgraph/Sales/index.ts:41]: This is `sellAmount`

File: src/subgraph/attributes.ts [hunk 7]
```diff
@@ -47,7 +47,7 @@ export const FAIR_PRICE_SALE_FIELDS = gql`
     status
     startDate
     endDate
-    tokenAmount
+    tokensForSale
```
Comment (adamazad) [inline src/subgraph/attributes.ts:50]: `sellAmount`

File: src/components/Table/index.tsx [hunk 8]
```diff
@@ -76,26 +77,45 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
-                        <TokenPriceLabel>{purchase[element]}</TokenPriceLabel>
-                      </TableColumn>
-                    )
-                  })}
+                  {Object.getOwnPropertyNames(purchase)
+                    .filter(skip => skip !== 'status')
+                    .map((element: any, _index) => {
+                      return (
+                        <TableColumn key={_index}>
+                          <TokenPriceLabel>{purchase[element]}</TokenPriceLabel>
```
Comment (adamazad) [inline src/components/Table/index.tsx:91]: Avoid `any` and cast the type using `keyof`

```suggestion
                          <TokenPriceLabel>{purchase[element as keyof purchase]}</TokenPriceLabel>
```

File: src/contexts/index.tsx [hunk 9]
```diff
@@ -1,6 +1,8 @@
 /* eslint-disable @typescript-eslint/no-unused-vars */
 import React from 'react'
 
+export const ClaimContext = React.createContext('SUBMITTED')
```
Comment (adamazad) [inline src/contexts/index.tsx:4]: Why do we need this? Where is it used?

File: src/hooks/useBids.ts [hunk 10]
```diff
@@ -24,7 +24,7 @@ interface UseBidsReturn {
   error: Error | null
   bids: SaleBid[]
   totalBids: SaleBid[]
-  totalPurchased(bids: SaleBid[]): Pick<FixedPriceSalePurchase, 'buyer' | 'amount'>[]
+  totalPurchased(bids: any[]): Pick<FixedPriceSalePurchase, 'buyer' | 'amount' | 'status'>[]
```
Comment (adamazad) [inline src/hooks/useBids.ts:27]: No `any` types please.

File: src/hooks/useBids.ts [hunk 11]
```diff
@@ -40,7 +40,7 @@ export function useBids(saleId: string, saleType: SaleType): UseBidsReturn {
   const { bids: totalBids } = useChain(saleId, saleType)
   const bids = totalBids.filter((bid: any) => bid.buyer.toLowerCase() === account?.toLowerCase())
 
-  const totalPurchased = (bids: SaleBid[]) => {
+  const totalPurchased = (bids: any[]) => {
```
Comment (adamazad) [inline src/hooks/useBids.ts:43]: Refactor this out of the hook. It should be a simple reducer function.

File: src/hooks/useBids.ts [hunk 12]
```diff
@@ -40,7 +40,7 @@ export function useBids(saleId: string, saleType: SaleType): UseBidsReturn {
...
     const reduceTotalAmount = bids.reduce((accumulator: any, purchases: any) => {
```
Comment (adamazad) [inline src/hooks/useBids.ts:44]: No `any` types

File: src/hooks/useBids.ts [hunk 13]
```diff
@@ -49,6 +49,7 @@ export function useBids(saleId: string, saleType: SaleType): UseBidsReturn {
       {
         buyer: account!,
         amount: reduceTotalAmount,
+        status: bids.length > 0 ? bids[0].status : null,
       },
     ]
```
Comment (adamazad) [inline src/hooks/useBids.ts:54]: The function name doesn't describe the return value. It should be clear what the function does.

**Review by adamazad — CHANGES_REQUESTED** [review]

File: src/subgraph/Sales/index.ts (hunk 6 above)
Comment (hhamud) [reply src/subgraph/Sales/index.ts:41]: I'm looking at the aqua-xdai-dev subgraph and there is no parameter available for sellAmount in fairsale?

File: src/subgraph/attributes.ts (hunk 7 above)
Comment (hhamud) [reply src/subgraph/attributes.ts:50]: I'm looking at the aqua-xdai-dev subgraph and there is no parameter available for sellAmount in fairsale?

File: src/components/Table/index.tsx (hunk 3 above)
Comment (hhamud) [reply src/components/Table/index.tsx:89]: Object. entries give me an array of both key and value pairs. I just want the keys. Do you want me to use Object. keys instead? but that would give me the same problem as before in a previous PR.

Comment (adamazad) [reply src/components/Table/index.tsx:89]: But you're using the values. If you don't need the keys, `Object.values` is another utility 

```
                      <TableColumn key={_index}>
                        <TokenPriceLabel>{purchase[element]}</TokenPriceLabel>
                      </TableColumn>
```

File: src/hooks/useBids.ts [hunk 14]
```diff
@@ -24,7 +24,20 @@ interface UseBidsReturn {
...
+    return BigNumber.from(accumulator).add(purchases.amount)
+  }, BigNumber.from(0))
+
+  return [
+    {
+      buyer: account!,
+      amount: reduceTotalAmount,
+      status: bids.length > 0 ? bids[0].status : undefined,
+    },
+  ]
```
Comment (adamazad) [inline src/hooks/useBids.ts:40]: I am still confused about the purchase of this function. Please document your code from now on.

Why does it return an array when it's aggregating data? This is not ideal.

Comment (hhamud) [reply src/hooks/useBids.ts]: I was taking a shortcut in creating this array. its just easier to simply map over everything rather than stopping and checking to see if its either an array of objects or just an object. 

I will remove the array and update the other components.

File: src/components/Table/index.tsx [hunk 15]
```diff
@@ -75,26 +80,44 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
+                    })}
                   {isClosed ? (
                     <Flex flex={isMobile ? 1 : 2.5} justifyContent="center">
-                      <IconImg src={WarningSVG} margin={'4px 4px 4px 8px'} />
-                      {!isMobile && (
-                        <TokenPriceLabel color="#000629" padding="4px 8px 4px 0">
-                          Unclaimed
-                        </TokenPriceLabel>
+                      {purchase.status === 'CLAIMED' ? (
+                        <Fragment>
```
Comment (adamazad) [inline src/components/Table/index.tsx]: Fragments

File: src/components/Table/index.tsx [hunk 16]
```diff
@@ -75,26 +80,44 @@ export const Table = ({ headData, bodyData, isClosed }: TableProps) => {
...
+                            margin={isMobile ? '4px 32px 4px 0px' : '4px 4px 4px 8px'}
+                          />
+                          {!isMobile && (
+                            <TokenPriceLabel color="#4B9E98" padding="4px 8px 4px 0">
+                              Claimed
+                            </TokenPriceLabel>
+                          )}
+                        </Fragment>
+                      ) : (
+                        <Fragment>
```
Comment (adamazad) [inline src/components/Table/index.tsx]: Fragments.

File: src/hooks/useBids.ts [hunk 17]
```diff
@@ -24,7 +24,20 @@ interface UseBidsReturn {
...
```
Comment (adamazad) [inline src/hooks/useBids.ts]: We shouldn't have a hook exporting other than hooks. It's fine for now though.

**Review by adamazad — APPROVED** [review]
