### PR TITLE
Bug/auction switch

### LINKED ISSUE #121: Bug: Error when switching auction types
## Description

When the user switches between auction types, the bid data does not update and this causes the component to crash.

## Expected Behavior

The auctions should appear when clicked on

## Actual Behavior

The bidlist component crashes and causes an error

## Possible Fix
This could be an issue with how the react-redux. Although I am not entirely sure why this happens. 

## Steps to Reproduce

1. click on fairsale or fixedpricesale auction card
2. enter the auction
3. return to the home page
4. click on the opposite auction type
5. Component crashes

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* closes #121
* updated `mock` server to display a single `fairSale` and `fixedPriceSale` auction to mock some persistance

## How Has This Been Tested?

Tested manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/interfaces/Auction.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ interface BaseAuction {
 interface Bid {
   id: string
   status: string // submitted/settled/cancelled/claimed
-  BaseAuction: string
+  BaseAuction: BaseAuction
```
Comment (adamazad) [inline src/interfaces/Auction.ts:18]: In a future chores PR, let's drop the word Auction entirely.

File: src/redux/bidData/index.ts [hunk 2]
```diff
@@ -20,12 +20,21 @@ export enum ActionTypes {
...
 
+// indexable type
+export interface BidsBySaleId {
+  // "ox223123nlda": {"lastupdated", "bids: []"}
+  [saleId: string]: {
+    lastUpdated: number // UTC timestamp
+    bids: AuctionBid[] // bids
+  }
+}
+
```
Comment (adamazad) [inline src/redux/bidData/index.ts:31]: Let's not confuse `Auction` with `Sale`.

File: src/redux/bidData/index.ts [hunk 3]
```diff
@@ -89,7 +105,7 @@ export function BidReducer(state: BidState = defaultState, action: BidActionType
       return {
         ...state,
         isLoading: false,
-        bids: action.payload,
+        bidsBySaleId: { ...state.bidsBySaleId, ...action.payload },
```
Comment (adamazad) [inline src/redux/bidData/index.ts:108]: It's better that we don't move `bidsBySaleId` too much around. Narrow down the reducer.

File: src/views/Auction/index.tsx [hunk 4]
```diff
@@ -101,10 +103,15 @@ export function AuctionView() {
     return auctions
   })
 
-  const bids = useSelector<RootState, AuctionBid[]>(state => {
-    return state.BidReducer.bids
+  const bidsbySale = useSelector<RootState, any>(state => {
+    return state.BidReducer.bidsBySaleId[params.auctionId]
   })
```
Comment (adamazad) [inline src/views/Auction/index.tsx:108]: Chore: [use `camelCase` for functions and variable names](https://github.com/cryptonative-ch/mesa-interface/blob/main/CONTRIBUTING.md#naming-convention)

File: src/views/Auction/FixedPrice.tsx [hunk 5]
```diff
@@ -101,10 +104,12 @@ export function FixedPriceAuctionView() {
     return auctions
   })
 
-  const bids = useSelector<RootState, AuctionBid[]>(state => {
-    return state.BidReducer.bids
+  const bidsbySale = useSelector<RootState, any>(state => {
+    return state.BidReducer.bidsBySaleId[params.auctionId]
   })
```
Comment (adamazad) [inline src/views/Auction/FixedPrice.tsx:109]: [Naming convention](https://github.com/cryptonative-ch/mesa-interface/blob/main/CONTRIBUTING.md#naming-convention)

File: src/redux/bidData/index.ts [hunk 6]
```diff
@@ -39,7 +48,7 @@ export const initialBidRequest = (payload: boolean) => ({
   type: ActionTypes.INITIAL_BID_REQUEST,
 })
 
-export const initialBidSuccess = (payload: AuctionBid[]) => ({
+export const initialBidSuccess = (payload: BidsBySaleId) => ({
   payload,
   type: ActionTypes.INITIAL_BID_SUCCESS,
 })
```
Comment (adamazad) [inline src/redux/bidData/index.ts:54]: This action expects that the line calling it to know about and pass previous Redux state (precisely `store.bidData.bids`). Actions shouldn't accept previous data from the redux.

**Review by adamazad — CHANGES_REQUESTED** [review]

File: src/redux/bidData/index.ts (hunk 3 above)
Comment (hhamud) [reply src/redux/bidData/index.ts:108]: What do you mean by
 >Narrow down the reducer?

In this part, I was thinking of having the redux store each sequential bid and updating the store with new bids rather than requesting the entire history on each fetch.

File: src/redux/bidData/index.ts (hunk 6 above)
Comment (hhamud) [reply src/redux/bidData/index.ts:54]: I can only call this action when I make a request to the subgraph and so I don't pass any previous states into this action. Its only called by this function 

```typescript

export const fetchSaleBids = (id: string, saleType: saleType, saleBidsRequest: Promise<any>): AppThunk => {
  return async dispatch => {
    dispatch(initialBidRequest(true))
    try {
      dispatch(initialBidSuccess(await generateInitialSaleData(saleBidsRequest, saleType)))
    } catch (error) {
      console.log(error)
      dispatch(initialBidFailure(error))
    }
  }
}
```

Can you elaborate more on what the optimal way to write this piece of code in?

File: src/redux/bidData/index.ts (hunk 3 above)
Comment (hhamud) [reply src/redux/bidData/index.ts]: I've reworked this part now

File: abis/FairSale.json [hunk 7]
```diff
@@ -159,7 +159,7 @@
       {
         "indexed": false,
         "internalType": "uint96",
-        "name": "auctionedTokens",
+        "name": "saleedTokens",
```
Comment (adamazad) [inline abis/FairSale.json:162]: How did you update this ABI? Mesa contracts do not have the varaible `saleedTokens`. ` Get them from the artifacts and run `build-abis.sh` then update typechain types.

File: src/redux/store.ts [hunk 8]
```diff
@@ -16,7 +16,7 @@ declare module 'react-redux' {
 const rootReducer = combineReducers({
   page,
   BidReducer,
-  AuctionReducer,
+  SaleReducer,
 })
```
Comment (adamazad) [inline src/redux/store.ts:20]: Use `camelCase`  for the reducer names. Start by changing the exported names.

```typescript
const rootReducer = combineReducers({
  page,
  bid: bidReducer,
  sale: saleReducer,
})
```

File: src/router/index.tsx [hunk 9]
```diff
@@ -23,12 +23,12 @@ export const AppRouter = () => {
...
   return (
     <Switch>
-      <Route exact path="/" component={AuctionsView} />
-      <Route exact path="/auctions" component={AuctionsView} />
-      <Route exact path="/auctions/:auctionId" component={AuctionView} />
-      <Route exact path="/auctions/fixed/:auctionId" component={FixedPriceAuctionView} />
+      <Route exact path="/" component={SalesView} />
+      <Route exact path="/sales" component={SalesView} />
+      <Route exact path="/sales/:saleId" component={SaleView} />
+      <Route exact path="/sales/fixed/:saleId" component={FixedPriceSaleView} />
```
Comment (adamazad) [inline src/router/index.tsx:29]: Create a sub-router `<Switch>` for sales. Determine the sale type, and then pass the route params to that view. There is no need to put the sale type in the URL. It will create scaling issues: with every new sale mechanism, the routing table has to be updated.

File: src/router/index.tsx [hunk 10]
```diff
@@ -23,12 +23,12 @@ export const AppRouter = () => {
...
       <Route exact path="/about" component={StaticView} />
-      <Route exact path="/contact" component={AuctionsView} />
+      <Route exact path="/contact" component={SalesView} />
```
Comment (adamazad) [inline src/router/index.tsx:31]: `/contact` should use `ContactView`. It seems like this chore was executed by replacing every `Auction` keyword with `Sale`. This could have undesirable effects.

File: src/subgraph/SaleBids/index.ts [hunk 11]
```diff
@@ -1,8 +1,8 @@
-export const auctionBidsQuery = (auctionid: string, auctionType: 'fixedPriceSale' | 'fairSale') => {
-  if (auctionType == 'fixedPriceSale') {
+export const saleBidsQuery = (saleid: string, saleType: 'fixedPriceSale' | 'fairSale') => {
```
Comment (adamazad) [inline src/subgraph/SaleBids/index.ts:1]: `camelCase`

File: src/subgraph/SaleBids/index.ts [hunk 12]
```diff
@@ -18,7 +18,7 @@ export const auctionBidsQuery = (auctionid: string, auctionType: 'fixedPriceSale
 
   return `
 {
-  fairSale (id: ${JSON.stringify(auctionid)}) {
+  fairSale (id: ${JSON.stringify(saleid)}) {
```
Comment (adamazad) [inline src/subgraph/SaleBids/index.ts]: `camelCase`

File: src/subgraph/SaleBids/index.ts [hunk 13]
```diff
@@ -1,8 +1,8 @@
-export const auctionBidsQuery = (auctionid: string, auctionType: 'fixedPriceSale' | 'fairSale') => {
-  if (auctionType == 'fixedPriceSale') {
+export const saleBidsQuery = (saleid: string, saleType: 'fixedPriceSale' | 'fairSale') => {
+  if (saleType == 'fixedPriceSale') {
     return `
       {
-        fixedPriceSale (id: ${JSON.stringify(auctionid)}) {
+        fixedPriceSale (id: ${JSON.stringify(saleid)}) {
```
Comment (adamazad) [inline src/subgraph/SaleBids/index.ts]: `camelCase`

File: src/subgraph/index.ts [hunk 14]
```diff
@@ -4,18 +4,18 @@
 import axios from 'axios'
 
 //interface
-import { Auction, auctionType } from '../interfaces/Auction'
-import { BidsBySaleId } from 'src/redux/bidData'
+import { Sale, saleType } from '../interfaces/Sale'
+import { BidsBySaleId } from 'src/redux/BidData'
```
Comment (adamazad) [inline src/subgraph/index.ts:8]: Enums should be `TitleCase`.

**Review by adamazad — CHANGES_REQUESTED** [review]
