### PR TITLE
Bug/clearingprice

### LINKED ISSUE #128: Refactor ClearingPrice calculations on FairSale
## Description
ClearingPrice calculations needs to be checked to make sure that it corresponds to what the smart contracts do. It currently also has a problem of defaulting to 1/0 = infinity when the bids are loading and the component only updates on refresh of the page. 

## Expected Behavior

it should show the clearingprice calculation as bids enter the sake

### LINKED ISSUE #139: Fix Timer Issue
## Description

Remove lee's old timers as it does not account for daylight savings time

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* closes #128 
* closes #139
* replaces functions across components to enforce consistency
* introduced mapping for timezone abbreviations

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 1]
```diff
@@ -124,23 +124,27 @@ export function SelfBidList({ sale, clearingPrice, bids, isFixed }: SelfBidListP
       formatBigInt(clearingPrice.tokenOut, sale.tokenOut.decimals)
     : 0
 
-  if (isFixed && isSaleOpen(sale)) {
+  if (isFixed) {
     return (
       <Flex flexDirection="column" style={{ position: 'relative' }}>
         <Flex flexDirection="row" alignItems="center" marginBottom="8px" padding={isMobile ? '0 8px' : '0 16px'}>
```
Comment (adamazad) [inline src/views/Sale/components/SelfBidList/index.tsx:130]: Not a priority, but we should unify the viewport breakpoints.

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 2]
```diff
@@ -124,23 +124,27 @@ export function SelfBidList({ sale, clearingPrice, bids, isFixed }: SelfBidListP
...
             <ColumnLabel>Value</ColumnLabel>
           </Flex>
+          {isSaleClosed(sale) ? (
+            <Flex flex={isMobile ? 1 : 3} flexDirection="row" alignItems="center" justifyContent="flex-end">
+              <ColumnLabel>Status</ColumnLabel>
+            </Flex>
+          ) : null}
         </Flex>
 
         {bids.map((bid: SaleBid, index: number) => {
```
Comment (adamazad) [inline src/views/Sale/components/SelfBidList/index.tsx:147]: Types are inferred.

File: src/views/Sale/components/Timer/index.tsx [hunk 3]
```diff
@@ -12,6 +19,14 @@ import { isSaleOpen, isSaleUpcoming } from 'src/mesa/sale'
...
 // Utils
 import { convertUtcTimestampToLocal } from 'src/utils/date'
+import { timezoneAbbreviation } from 'src/utils/timezone'
+
+dayjs.extend(advanced)
+dayjs.extend(utc)
+dayjs.extend(timezone)
+dayjs.extend(advanced)
+dayjs.extend(relativeTime)
+dayjs.extend(durationTime)
```
Comment (adamazad) [inline src/views/Sale/components/Timer/index.tsx:29]: These are set up/configuration calls. Let's move these to `src/App.ts` or `src/index.ts`

**Review by adamazad — APPROVED** [review]
Let's merge it for now. Comments for a future PR.
