### PR TITLE
Bug/withdraw

### LINKED ISSUE #249: Fix Withdraw Buttons on FixedPriceSale
## Description
* Fix Withdraw Buttons on FixedPriceSale 

## Expected Behavior
It should be smaller and be dynamic, switching from withdraw bid and claim bid depending on the threshold of the sale

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by hhamud**
---
name: Pull Request
about: Create a pull request for this project

---

## Description
* closes #249 
* Refactored `SelfBidList` Component

## How Has This Been Tested?
Tested Manually

## Screenshots (if appropriate):
Open Sale
image

Closed Sale
image

Mobile View Open Sale
image

Mobile View closed Sale
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 1]
```diff
@@ -128,13 +128,13 @@ export function SelfBidList({ sale, clearingPrice, bids, isFixed }: SelfBidListP
     return (
       <Flex maxHeight="200px" flexDirection="column" style={{ position: 'relative' }}>
         <Flex flexDirection="row" alignItems="center" marginBottom="8px" padding={isMobile ? '0 8px' : '0 16px'}>
-          <Flex flex={isMobile ? 2.5 : 3}>
+          <Flex flex={isMobile ? 2.5 : 3} justifyContent="center">
```
Comment (rossneilson) [inline src/views/Sale/components/SelfBidList/index.tsx:131]: It might make more sense to just create a new styled component for all these.
You can extend Flex and then just add justifyContent as the only difference

File: src/views/Sale/components/SelfBidList/index.tsx [hunk 2]
```diff
@@ -124,21 +124,93 @@ export function SelfBidList({ sale, clearingPrice, bids, isFixed }: SelfBidListP
...
+
+            return (
+              <Flex
+                key={index}
+                flexDirection="row"
+                alignItems="center"
+                minHeight="50px"
+                borderTop="1px dashed #DDDDE3"
+                padding={isMobile ? '0 8px' : '0 16px'}
+              >
```
Comment (rossneilson) [inline src/views/Sale/components/SelfBidList/index.tsx:157]: I also think something like this works better being defined as a separate styled component, makes it more readable

Comment (rossneilson) [reply src/views/Sale/components/SelfBidList/index.tsx:157]: Since there are a lot of them above a style.tsx might be a good addition

**Review by rossneilson — COMMENTED** [review]
I think generally also this component should be split up at made into more re-usable modular parts. Looks like a lot of repetition and quite long also

File: src/components/Table/index.tsx [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+
+  const toggleBidMenu = (index: number) => {
+    if (tableMenu === index) {
+      setBidMenu(-1)
+      return
+    }
+    setBidMenu(index)
+  }
+  // <InfoImg src={InfoSVG} />
+  // <IconImg src={MoreSVG} marginRight="8px" isButton={true} onClick={() => toggleBidMenu(index)} />
```
Comment (rossneilson) [inline src/components/Table/index.tsx:165]: Should probably remove commented code

File: src/views/Sale/components/SelfBidList/index.spec.tsx [hunk 4]
```diff
@@ -24,7 +24,7 @@ dayjs.extend(relativeTime)
 dayjs.extend(durationTime)
 
 describe('SelfBidList', () => {
-  test('should display texts', () => {
+  test.skip('should display texts', () => {
```
Comment (rossneilson) [inline src/views/Sale/components/SelfBidList/index.spec.tsx:27]: Why are we skipping this test?

File: src/components/Table/index.tsx [hunk 5]
```diff
@@ -0,0 +1,219 @@
...
+  flexDirection: 'row',
+  alignItems: 'center',
+  marginBottom: '8px',
+})
+
+const TableBody = styled(Flex)({
+  overflowY: 'scroll',
+  flexDirection: 'column',
+})
+
```
Comment (rossneilson) [inline src/components/Table/index.tsx:131]: Not super important, but for future, if we have a large number of styled components like this it may make sense to add them into a styled.tsx file like with other components

**Review by rossneilson — COMMENTED** [review]
This looks neater to me, nice job.
Just the small comments below to change.

File: src/components/Table/index.tsx [hunk 6]
```diff
@@ -0,0 +1,219 @@
...
+      </TableHead>
+      <TableBody>
+        {bodyData.map(({ purchases, color, title }) =>
+          purchases.map((purchase: any, index) => {
+            return (
+              <TableRow key={index} padding={isMobile ? '0 8px' : '0 16px'}>
+                <TableColumn>
+                  <TokenPriceLabel color={color}>{title}</TokenPriceLabel>
+                </TableColumn>
+                {Object.getOwnPropertyNames(purchase).map((element: any, _index) => {
```
Comment (rossneilson) [inline src/components/Table/index.tsx:186]: I have only ever used keys() for this but I guess getOwnPropertyNames works too

File: src/components/Table/index.tsx [hunk 7]
```diff
@@ -1,133 +1,28 @@
...
+  HeaderColumn,
+  ColumnLabel,
+  TableBody,
+  TableRow,
+  TableColumn,
+  TokenPriceLabel,
+  IconImg,
+  ModalContainer,
+  ModalMenu,
+} from './style'
```
Comment (rossneilson) [inline src/components/Table/index.tsx:24]: We should try to keep imports consistently absolute if we can.
so src/components/Table/style

File: src/views/Sale/components/SelfBidList/index.spec.tsx (hunk 4 above)
Comment (hhamud) [reply src/views/Sale/components/SelfBidList/index.spec.tsx:27]: I wanted to leave refactoring the tests to a later PR.

File: src/components/Table/index.tsx (hunk 6 above)
Comment (hhamud) [reply src/components/Table/index.tsx:77]: [It was brought up in a previous PR](https://github.com/cryptonative-ch/mesa-interface/pull/150#discussion_r630342546). If I want consistency then I shouldn't use keys().

File: src/components/Table/index.tsx (hunk 7 above)
Comment (hhamud) [reply src/components/Table/index.tsx:24]: Bad Habit I always forget to include these little things. Maybe adding them as custom rules into the eslint will help?

Comment (rossneilson) [reply src/components/Table/index.tsx]: If it supports it then we definitely should

File: src/components/Table/index.tsx (hunk 6 above)
Comment (rossneilson) [reply src/components/Table/index.tsx:77]: Nice, thanks for linking this. I didn't know about it before :)
I have always just used keys and never had an issue with it.

File: src/views/Sale/components/SelfBidList/index.spec.tsx (hunk 4 above)
Comment (rossneilson) [reply src/views/Sale/components/SelfBidList/index.spec.tsx:27]: Sure, just make sure not to forget ;)
I am very good at "postponing" writing tests for react
